export const ERROR = "ERROR";
export const LOADING = "LOADING";
export const GET_CLIENTS_SUCCESS = "GET_CLIENTS_SUCCESS";
export const GET_PROVIDERS_SUCCESS = "GET_PROVIDERS_SUCCESS";
export const ADD_PROVIDER_SUCCESS = 'ADD_PROVIDER_SUCCESS'
export const ADD_CLIENT_SUCCESS = 'ADD_CLIENT_SUCCESS'
